//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Figures = new HashSet<Figure>();
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public int WhitePlayerId { get; set; }
        public Nullable<int> BlackPlayerId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> UserIdInTurn { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Figure> Figures { get; set; }
        public virtual GameStatus GameStatus { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
