//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Games = new HashSet<Game>();
            this.Games1 = new HashSet<Game>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SessionKey { get; set; }
        public string AuthCode { get; set; }
        public string Nickname { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
        public virtual ICollection<Game> Games1 { get; set; }
    }
}
