//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStringService")]
public interface IStringService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/CountSubstringOccurrences", ReplyAction="http://tempuri.org/IStringService/CountSubstringOccurrencesResponse")]
    int CountSubstringOccurrences(string subString, string mainString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/CountSubstringOccurrences", ReplyAction="http://tempuri.org/IStringService/CountSubstringOccurrencesResponse")]
    System.Threading.Tasks.Task<int> CountSubstringOccurrencesAsync(string subString, string mainString);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStringServiceChannel : IStringService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StringServiceClient : System.ServiceModel.ClientBase<IStringService>, IStringService
{
    
    public StringServiceClient()
    {
    }
    
    public StringServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StringServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int CountSubstringOccurrences(string subString, string mainString)
    {
        return base.Channel.CountSubstringOccurrences(subString, mainString);
    }
    
    public System.Threading.Tasks.Task<int> CountSubstringOccurrencesAsync(string subString, string mainString)
    {
        return base.Channel.CountSubstringOccurrencesAsync(subString, mainString);
    }
}
