//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Figure
    {
        public int Id { get; set; }
        public int PositionRow { get; set; }
        public int PositionCol { get; set; }
        public int TypeId { get; set; }
        public bool IsWhite { get; set; }
        public int GameId { get; set; }
        public bool IsMoved { get; set; }
    
        public virtual FigureType FigureType { get; set; }
        public virtual Game Game { get; set; }
    }
}
