USE [master]
GO

/****** Object:  Database [Supermarkets]    Script Date: 7/23/2013 13:37:44 ******/
CREATE DATABASE [Supermarkets]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Supermarkets', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Supermarkets.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Supermarkets_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Supermarkets_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Supermarkets] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Supermarkets].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Supermarkets] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Supermarkets] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Supermarkets] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Supermarkets] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Supermarkets] SET ARITHABORT OFF 
GO

ALTER DATABASE [Supermarkets] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Supermarkets] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Supermarkets] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Supermarkets] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Supermarkets] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Supermarkets] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Supermarkets] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Supermarkets] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Supermarkets] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Supermarkets] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Supermarkets] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Supermarkets] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Supermarkets] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Supermarkets] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Supermarkets] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Supermarkets] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Supermarkets] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Supermarkets] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Supermarkets] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Supermarkets] SET  MULTI_USER 
GO

ALTER DATABASE [Supermarkets] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Supermarkets] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Supermarkets] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Supermarkets] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Supermarkets] SET  READ_WRITE 
GO

