//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int UserId { get; set; }
        public bool IsMsgRead { get; set; }
        public int MsgTypeId { get; set; }
        public int GameId { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual MessagesType MessagesType { get; set; }
    }
}
