//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketManagement {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..//..//ExternalData//Sales-Reports.zip")]
        public string ZipReportsPath {
            get {
                return ((string)(this["ZipReportsPath"]));
            }
            set {
                this["ZipReportsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..//..//ExternalData//TempExtract")]
        public string ZipReportsExtractPath {
            get {
                return ((string)(this["ZipReportsExtractPath"]));
            }
            set {
                this["ZipReportsExtractPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..//..//PdfExports")]
        public string PdfExportPath {
            get {
                return ((string)(this["PdfExportPath"]));
            }
            set {
                this["PdfExportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..//..//XmlExports//Report.xml")]
        public string XmlReportExtractPath {
            get {
                return ((string)(this["XmlReportExtractPath"]));
            }
            set {
                this["XmlReportExtractPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..//..//Product-Reports")]
        public string JsonExportPath {
            get {
                return ((string)(this["JsonExportPath"]));
            }
            set {
                this["JsonExportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://localhost")]
        public string MongoDbConnectionString {
            get {
                return ((string)(this["MongoDbConnectionString"]));
            }
            set {
                this["MongoDbConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..//..//ExcelExports//Products-Total-Report.xlsx")]
        public string ExcelExportTotalProductReportPath {
            get {
                return ((string)(this["ExcelExportTotalProductReportPath"]));
            }
            set {
                this["ExcelExportTotalProductReportPath"] = value;
            }
        }
    }
}
