//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSQLEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDetail
    {
        public int ReportDetailId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public int ReportId { get; set; }
        public int ProductId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Report Report { get; set; }
    }
}
